"""worker leases and run idempotency

Revision ID: 809aa1e3b32b
Revises: 166faaad94d3
Create Date: 2026-07-15 10:15:28.046621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '809aa1e3b32b'
down_revision: Union[str, Sequence[str], None] = '166faaad94d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('idempotency_key', sa.Text(), nullable=False))
    op.add_column('runs', sa.Column('lease_token', sa.BigInteger(), nullable=False))
    op.add_column('runs', sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.create_unique_constraint('uq_runs_task_idempotency_key', 'runs', ['task_id', 'idempotency_key'])
    op.add_column('tasks', sa.Column('assigned_agent_version_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('lease_owner', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('lease_token', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('tasks', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_tasks_assigned_agent_version_id_agent_versions'), 'tasks', 'agent_versions', ['assigned_agent_version_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tasks_assigned_agent_version_id_agent_versions'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'lease_expires_at')
    op.drop_column('tasks', 'lease_token')
    op.drop_column('tasks', 'lease_owner')
    op.drop_column('tasks', 'assigned_agent_version_id')
    op.drop_constraint('uq_runs_task_idempotency_key', 'runs', type_='unique')
    op.drop_column('runs', 'snapshot')
    op.drop_column('runs', 'lease_token')
    op.drop_column('runs', 'idempotency_key')
    # ### end Alembic commands ###
