"""task graph scheduling metadata

Revision ID: a87a36f04b50
Revises: 809aa1e3b32b
Create Date: 2026-07-15 13:12:23.678111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a87a36f04b50'
down_revision: Union[str, Sequence[str], None] = '809aa1e3b32b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('expected_outputs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('tasks', sa.Column('resource_intent', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('tasks', sa.Column('policy_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('tasks', sa.Column('budget_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_tasks_budget_id_budgets'), 'tasks', 'budgets', ['budget_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tasks_budget_id_budgets'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'budget_id')
    op.drop_column('tasks', 'policy_ids')
    op.drop_column('tasks', 'resource_intent')
    op.drop_column('tasks', 'expected_outputs')
    # ### end Alembic commands ###
